### ISSUE TITLE
l4d repository

### ISSUE THREAD

**Issue by CaptainMack** [Left4DevOps/l4d2-docker#12]
Dear devs,

I was wondering whether you could create a repo for the l4d image as well? I want to see if I can compile it for arm64 to run a RPI4.

**Comment by hazmeister** [comment]
This repo can build the original l4d too- see https://github.com/Left4DevOps/l4d2-docker/blob/master/build-l4d.sh

I haven’t had any luck getting this to run on a raspberry pi yet, with qemu, but there’s another repo which looks like it might work - https://github.com/potatoenergy/l4d2-docker

I haven’t played with it yet, but it looks like box86 does the heavy lifting where previously I’ve tried qemu. It might be something I can bring into this image to make it multi format in the future.

**Comment by CaptainMack** [comment]
Thank you @hazmeister I'll take a look and see if it's possible!
