### ISSUE TITLE
How to use start flags in docker compose?

### ISSUE THREAD

**Issue by brielov** [Left4DevOps/l4d2-docker#7]
So for example I would like to run the server in versus mode only. The question would be how can I replicate something like `docker run left4devops/l4d2 -port 27020 +map "c14m1_junkyard" +sv_lan 1` but in the docker compose file?

**Comment by hazmeister** [comment]
Just pushed a new image. You can now set the game mode by setting the `DEFAULT_MODE` environment variable.

if you still want to override the launch options, you can use `command:` in docker-compose.yml
